// Integration connection status
export interface Integration {
  id: string;
  name: string;
  description: string;
  connected: boolean;
  connectionId?: string;
}

// Extracted details from AI parsing of description
export interface ExtractedDetails {
  clientName: string;
  projectName: string;
  projectType: 'claims' | 'support' | 'sales' | 'faq' | 'survey' | 'custom';
  botPurpose: string;
  keyFeatures: string[];
  targetCompany: string;
  description: string;
}

// Custom script type for action nodes
export interface CustomScript {
  name: string;
  content: string;
}

// Validation error with row details
export interface FailedRow {
  nodeNum: number;
  rowNum: number;
  nodeName?: string;
  nodeType?: string;
  errors: string[];
  rawRow?: string;
  fields?: Record<string, string>;
}

// Health check result from post-deployment verification
export interface HealthCheckResult {
  healthy: boolean;
  firstMessage?: string;
  errorDetected: boolean;
  errorType?: 'technical_difficulties' | 'no_agents' | 'unknown';
  details?: string;
}

// Result from instant build pipeline
export interface InstantBuildResult {
  success: boolean;
  widgetUrl?: string;
  widgetId?: string;
  sheetsUrl?: string;
  spreadsheetId?: string;
  nodeCount: number;
  botId: string;
  versionId?: string;
  error?: string;
  csv?: string;
  // Custom scripts generated by AI or edited by user
  scripts?: CustomScript[];
  // Cached generation data for pipeline resume after auth errors
  _cachedGeneration?: any;
  // Human intervention flags for cases AI can't resolve
  needsHumanIntervention?: boolean;
  humanInterventionContext?: string;
  // Failed rows for manual debugging/fixing
  failedRows?: FailedRow[];
  // Post-deployment health check result
  healthCheck?: HealthCheckResult;
}

// Instant flow step type
export type InstantStep = 'create' | 'confirm' | 'architecture' | 'processing' | 'results' | 'editor';

// Brand assets from Brandfetch API
export interface BrandColor {
  name: string;
  hex: string;
  usage?: 'primary' | 'secondary' | 'accent' | string;
}

export interface BrandLogo {
  url: string;
  type: 'primary' | 'icon' | 'wordmark';
  format?: string;
  background?: 'light' | 'dark' | 'transparent';
}

export interface BrandFont {
  name: string;
  type: 'title' | 'body' | string;
  origin?: 'google' | 'custom' | string;
  originId?: string;
  weights?: number[];
}

export interface BrandAssets {
  name?: string;
  domain?: string;
  colors: BrandColor[];
  logos: BrandLogo[];
  fonts: BrandFont[];
  images: { url: string; type: string }[];
  primaryColor?: string;
  secondaryColor?: string;
  logoUrl?: string;
  logoBackground?: 'light' | 'dark' | 'transparent';
  brandMomentUrl?: string;
}

// Imported requirements from Figma/Sheets analysis
export interface ImportedRequirements {
  sections?: string[];
  dataFields?: string[];
  decisionPoints?: string[];
  userJourneys?: string;
  escalationTriggers?: string;
  dataCollection?: string;
  errorHandling?: string;
}

// Project configuration
export interface ProjectConfig {
  clientName: string;        // Always "CX" for bot ID purposes
  projectName: string;
  projectType: 'claims' | 'support' | 'sales' | 'faq' | 'survey' | 'custom';
  description: string;
  referenceFiles: FileUpload[];
  importedRequirements?: ImportedRequirements;
  targetCompany?: string;    // The actual company/brand (e.g., "Travelers Insurance")
  brandAssets?: BrandAssets; // Auto-detected from targetCompany via Brandfetch
  companyContext?: string;   // Company-specific knowledge for AI fallback
  botPersona?: string;       // Bot personality/persona for AI responses
}

export interface FileUpload {
  id: string;
  name: string;
  type: string;
  size: number;
  content?: string;
  url?: string;
}

// Clarifying questions from the AI
export interface ClarifyingQuestion {
  id: string;
  question: string;
  type: 'multiple_choice' | 'text' | 'boolean';
  options?: string[];
  answer?: string;
  reason?: string;
}

// Generated node from the solution
export interface BotNode {
  nodeNumber: number;
  nodeType: 'D' | 'A';
  nodeName: string;
  message?: string;
  richAssetType?: string;
  richAssetContent?: string;
  command?: string;
  parameterInput?: string;
  whatNext?: string;
  nextNodes?: string;
}

// Solution output
export interface Solution {
  id: string;
  nodes: BotNode[];
  csvContent: string;
  readme: string;
  // Google Sheets export
  spreadsheetId?: string;
  spreadsheetUrl?: string;
  // Deployment info
  customBotId?: string;  // User-edited Bot ID (overrides generated one)
  botUrl?: string;
  deployedEnvironment?: 'sandbox' | 'production';
  deployedVersionId?: string;
  // Validation
  validationResult?: ValidationResult;
  // Generated scripts (from AI generation)
  scripts?: { name: string; content: string }[];
  // Legacy validation from generation
  validation?: { valid: boolean; errors: string[] };
}

// AI-generated requirement question
export interface RequirementQuestion {
  id: string;
  question: string;
  options: { id: string; label: string }[];
  multiSelect?: boolean;
}

// Requirements answers (question id -> selected option ids)
export type RequirementsAnswers = Record<string, string[]>;

// Architecture editor state - saved to allow resuming work
export interface ArchitectureState {
  // Planned flows from the architecture review
  plannedFlows?: Array<{
    name: string;
    label?: string;
    description: string;
    startNode: number;
  }>;
  // Main menu options
  menuOptions?: Array<{
    label: string;
    description?: string;
    flowName?: string;
  }>;
  // Node positions in the visual editor (for exact restoration)
  nodePositions?: Record<string, { x: number; y: number }>;
  // Flow previews (conversation structures the user has seen/approved)
  flowPreviews?: Record<string, any[]>;
  // Whether generation has completed
  hasGenerated?: boolean;
  // Extracted project details
  extractedDetails?: ExtractedDetails;
  // Brand assets
  brandAssets?: BrandAssets;
  // Target company name (for generation context)
  targetCompany?: string;
  // Current instant step
  instantStep?: InstantStep;
  // Build result from generation (for View Solution popup)
  instantBuildResult?: InstantBuildResult;
}

// Saved solution for dashboard
export interface SavedSolution {
  id: string;
  name: string;
  clientName: string;
  projectType: 'claims' | 'support' | 'sales' | 'faq' | 'survey' | 'custom';
  description: string;
  createdAt: string;
  updatedAt: string;
  status: 'draft' | 'deployed' | 'archived';
  nodeCount: number;
  deployedEnvironment?: 'sandbox' | 'production';
  // Creation progress tracking
  currentStep?: WizardStep;
  // Requirements step data
  requirementsQuestions?: RequirementQuestion[];
  requirementsAnswers?: RequirementsAnswers;
  // Generated content
  csvContent?: string;
  csv?: string; // Alias for csvContent (for compatibility)
  // External links
  spreadsheetUrl?: string;
  botUrl?: string;
  widgetUrl?: string;
  // Deployment details
  widgetId?: string;
  botId?: string;
  versionId?: string;
  // Architecture editor state (for resuming work)
  architectureState?: ArchitectureState;
}

export interface ValidationResult {
  passed: boolean;
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
  stats: {
    totalNodes: number;
    decisionNodes: number;
    actionNodes: number;
  };
  // Official Bot Manager validation
  officiallyValidated?: boolean;
  versionId?: string;
  // Direct node counts (alternative to stats)
  decisionNodes?: number;
  actionNodes?: number;
}

export interface ValidationIssue {
  nodeNumber?: number;
  message: string;
  severity: 'error' | 'warning';
  // API dependency info for "Use Mock Data" feature
  apiDependency?: {
    type: 'bigquery' | 'email' | 'booking' | 'external_api' | 'integration';
    command?: string;
    affectedNodes?: number[];
    mockDataApplied?: boolean;
  };
}

// Wizard steps - removed 'integrations' step
export type WizardStep = 
  | 'welcome'
  | 'dashboard'
  | 'solution-detail'
  | 'project-setup'
  | 'requirements'
  | 'clarifying-questions'
  | 'generation'
  | 'review'
  | 'deploy';

// API credentials
export interface Credentials {
  pypestreamApiKey?: string;
  figmaToken?: string;
  // AI Provider API keys (user brings their own)
  anthropicApiKey?: string;
  googleAiApiKey?: string;
  // Which AI provider to use for generation
  aiProvider?: 'anthropic' | 'google';
}

// User profile
export interface UserProfile {
  name: string;
  email: string;
  avatar: string;
}

// App state
export interface AppState {
  currentStep: WizardStep;
  integrations: Integration[];
  credentials: Credentials;
  projectConfig: ProjectConfig;
  // Requirements step
  requirementsQuestions: RequirementQuestion[];
  requirementsAnswers: RequirementsAnswers;
  // Legacy clarifying questions
  clarifyingQuestions: ClarifyingQuestion[];
  solution: Solution | null;
  savedSolutions: SavedSolution[];
  activeSolutionId: string | null;
  isLoading: boolean;
  error: string | null;
  user: UserProfile;
  sidebarOpen: boolean;
  solutionsLoaded: boolean;
}

// ============================================
// Live Edit Types
// ============================================

// Message from the bot conversation
export interface ConversationMessage {
  id: string;
  text: string;
  fromSide: 'bot' | 'user';
  timestamp: Date;
  richAssetType?: string;
  richAssetContent?: any;
  nodeNum?: number;
}

// Current context of the conversation for the edit engine
export interface ConversationContext {
  messages: ConversationMessage[];
  lastBotMessage?: ConversationMessage;
  lastUserMessage?: ConversationMessage;
  currentNodeNum?: number;
  sessionActive: boolean;
  summary?: string;
}

// Edit request from the user
export interface EditRequest {
  instruction: string;
  context: ConversationContext;
  currentCsv: string;
  currentScripts: CustomScript[];
  targetNodeNum?: number;
}

// Result of an edit operation
export interface EditResult {
  success: boolean;
  modifiedCsv: string;
  modifiedScripts?: CustomScript[];
  changesSummary: string;
  affectedNodes: number[];
  error?: string;
}

// Editor chat message
export interface EditorMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  editResult?: EditResult;
  isLoading?: boolean;
}

// Live edit session state
export interface LiveEditSession {
  solutionId: string;
  botId: string;
  widgetId: string;
  widgetUrl: string;
  csv: string;
  scripts: CustomScript[];
  versionId?: string;
  editHistory: EditResult[];
}
